using Content.Shared._AR.Store.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._AR.Store;

[GenerateTypedNameReferences]
public sealed partial class ARStoreCategoryControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public readonly ARStoreCategoryPrototype Category;
    public ProtoId<ARStoreCategoryPrototype> CategoryId => Category.ID;

    public ARStoreCategoryControl(ProtoId<ARStoreCategoryPrototype> categoryId, ButtonGroup group, bool pressed)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Category = _prototype.Index(categoryId);

        SelectButton.Text = Category.LocName;
        SelectButton.Pressed = pressed;
        SelectButton.Group = group;
    }
}
