- type: tile
  baseTurf: ARFloorBase # Recursive indestructible
  id: ARFloorBase
  name: ar-tiles-base
  editorHidden: true
  sprite: /Textures/_AR/Tiles/grass/grass.png
  variants: 3
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 2
  edgeSprites:
    SouthEast: /Textures/_AR/Tiles/grass/grass_single_edge.png
    NorthEast: /Textures/_AR/Tiles/grass/grass_single_edge.png
    NorthWest: /Textures/_AR/Tiles/grass/grass_single_edge.png
    SouthWest: /Textures/_AR/Tiles/grass/grass_single_edge.png
    South: /Textures/_AR/Tiles/grass/grass_edge.png
    East: /Textures/_AR/Tiles/grass/grass_edge.png
    North: /Textures/_AR/Tiles/grass/grass_edge.png
    West: /Textures/_AR/Tiles/grass/grass_edge.png
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  indestructible: true
